### ISSUE TITLE
The RegEx for HTML tags does not match the HTML Headings tags

### ISSUE THREAD

**Issue by dineshb-qa** [lukehaas/RegexHub#10]
**Steps to Reproduce :**
- Go to [RegEx Site](https://projects.lukehaas.me/regexhub/)
- Go to HTML tags section and enter the test string as, HTML Heading tag : ```<h1>Heading</h1>``` (this is one of the valid tags as per [W3 School site](http://www.w3schools.com/TAGs/))
- Observe that the output returned is null
- **The RegEx should be : /^<([a-z][1-6]+)([^<]+)*(?:>(.*)<\/\1>|\s+\/>)$/** in order to match the HTML Headings tag

**Expected Result**
The RegEx for HTML tag should match all the HTML tags

**Actual Result**
The RegEx for HTML tags does not match the HTML headings tags

**Comment by lukehaas** [comment]
Thanks @dineshb-qa the HTML regex has been updated now.
