### ISSUE TITLE
Date regex doesn't validate dates < 1900 || > 2099

### ISSUE THREAD

**Issue by singuerinc** [lukehaas/RegexHub#3]
Maybe is a feature, but for me should be generic so that it validates all "valid" dates.
It doesn't work if you try to validate: "01/01/2100"

**Comment by Milewski** [comment]
Or bellow 1899..

**Comment by lukehaas** [comment]
Yeah, its currently more of a date of birth date checker, but you're probably right, it should validate all dates. I'll update it soon.

**Comment by lukehaas** [comment]
This is updated now.
